task:
  name: Test
  container:
    image: golang:latest
  get_script: go get -t -v ./...
  build_script: go build
  test_script: go test -v ./...

task:
  name: GolangCI Lint
  container:
    image: golangci/golangci-lint:latest
  run_script: golangci-lint run -v --out-format json > lint-report.json
  always:
    golangci_artifacts:
      path: lint-report.json
      type: text/json
      format: golangci